# Configuração da API Fusion
[api]
environment = "dev"  # Opções: "dev", "hml", "prod"
base_url_dev = "http://fusion-dev.carglass.dev.local:3000/api"
base_url_hml = "http://fusion-hml.carglass.hml.local:3000/api"
base_url_prod = "https://fusion.carglass.com.br/api"

# Configuração da API OpenAI (para IA)
[openai]
api_key = "sk-proj-"
model = "gpt-4"
api_endpoint = "https://api.openai.com/v1/chat/completions"

# Configuração do WhatsApp
[whatsapp]
api_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
phone_number_id = "xxxxxxxxxxxx"
api_version = "v17.0"
webhook_verify_token = "xxxxxxxxxxxx"  # Token para verificação do webhook

# Configuração de Redis (opcional para ambiente de produção)
[redis]
url = "redis://username:password@host:port"
prefix = "carglass-assistente:"
